### ISSUE TITLE
TypeError: io.set is not a function

### ISSUE THREAD

**Issue by mrbbp** [ffd8/P5LIVE#102]
i've got this error.
i've tested offline few days ago and it was ok (restart mac after this)
but now i've got this error...
i've got an apache running at localhost, event if i stop it, it does not work.

i'm a beat lost.
````
node server.js 5010

/Users/xxx/Downloads/P5LIVE-master/server.js:78
io.set('transports', ['websocket']); 
   ^

TypeError: io.set is not a function
    at Object.<anonymous> (/Users/xxx/Downloads/P5LIVE-master/server.js:78:4)
    at Module._compile (node:internal/modules/cjs/loader:1467:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49

Node.js v22.4.0
````
macos 14.7.1, M1

**Comment by mrbbp** [comment]
recent update to 14.7.1
don't know if it make sens

**Comment by ffd8** [comment]
@mrbbp did you by any chance run `npm audit fix --force` recently in the folder or do you have a global version of `socket.io` installed? I'm guessing you've accidentally had it update all the npm dependencies – which causes a problem if socket.io gets updated to latest, since there's some deprecated functions i'm currently using. eventually i'll get around to updating the socket.io version (while also switching the cocoding engine to yjs) – but just haven't taken the time for now, since 'it works'. A quick fix, might be to just re-download P5LIVE latest release v1.6.2, then try running `npm install`, then `npm start 5010` from within that new directory. If you had a custom `/data` folder in your old P5LIVE dir, copy it over.

**Comment by ffd8** [comment]
PS - could also just manually downgrade socket.io within the P5LIVE folder: `npm install socket.io@2.5.1`

**Comment by mrbbp** [comment]
Hello Ted,

yes i did `npm audit fix --force` as a good little soldier, so your solution to redownload + install old socket.io works.
but i have an other issue about port number in use. i received a message that there is a other osc running at... but it works now.
`CTRL + C` kill the server and other subroutine osc etc? i do not find a `npm stop` or a way to stop server (npm is a beat magic for me, don't know if it black or white ;) )
regards
