### ISSUE TITLE
Midi CC values > 120 are not passed through to p5live patch

### ISSUE THREAD

**Issue by kaosbeat** [ffd8/P5LIVE#109]
Doing some midi to P5live I noticed that midi CC number > 120 are not passed through to P5.

I can see them fine in my midilogger (protokol) just fine
tested on multiple PCs with both off and online versions

so 
```
{
    "type": "controlchange",
    "channel": 1,
    "number": 120,     <------------------------ this one here
    "name": "generalpurposeslider1",
    "value": 127
}
```

the whole message is simply ignored if cc.number >120
I just used the midi_custom patch to test this behaviour and it is also there

I found this line 
`new RangeError("The control change number must be between 120 and 127.");`

in `P5LIVE/includes/utils/p5live-midi.js`

but it is not really editable code for me,  maybe it has got to do something with that.

**Comment by ffd8** [comment]
Interesting.. [quick search](https://nickfever.com/music/midi-cc-list) for controlchange midi numbers, shows that 120-127 are treated differently for special system messages. Which I guess you're also trying to react upon? And bummer.. I'm using webmidi.js v2, since it's sooooo much smaller than v3 (embeddable in that `p5live-midi.js` for simplicity) and it somehow was smoother as an instance.. a few global/scope/etc reasons.. however, I see that in v2, it's specifically [filtering any CC numbers above 120](https://github.com/djipco/webmidi/blob/1e05555718f19742e666b9419590c2c3eff2e8df/src/webmidi.js#L2024)! Ahaa – which is then a `channelmode`, not a `controlchange` = this parser just has to be ready for those messages too.. never dealt with them in my analysis.. I guess you are? I'm also ignoring programchange etc etc... so it's really intended for just QUIICK implementation for folks that want to quickly visualize their notes and control changes.. of course I can quickly pass along the rest.. or even 'raw' for more advanced custom use?

**Comment by ffd8** [comment]
PS - nice sandbox for testing: https://midi-control.morningstar.io/web-midi-controller

**Comment by ffd8** [comment]
Yeah – I guess CC #120+ should be reserved for those program changes, since gear likely also goes wild when receiving them. Nevertheless, I'll reimplement the raw midimessage for instances like this.
