### ISSUE TITLE
Keyboard shortcuts in Windows and Linux

### ISSUE THREAD

**Issue by JunShern** [ffd8/P5LIVE#25]
Hi, me again! 

I may be missing something very obvious, but I have been struggling to get a hang of keyboard shortcuts in P5LIVE. 

In particular, I have been unable to get the following keyboard shortcuts (which I expect to be universal) to work:
- Copy (`Ctrl + C`)
- Jump to line start (`Home`)
- Jump to line end (`End`)

I have tested these on my own local hosted P5LIVE setup and http://p5live.org, on both Chrome and Firefox, as well as in both Linux and Windows environments.

In all environments tested so far, the 3 commands above do nothing. But strangely, their close relatives are working fine for me:
- Paste (`Ctrl + V`) works!
- Selection to line start (`Shift + Home`) works!
- Selection to line end (`Shift + End`) works!

**Comment by ffd8** [comment]
Perhaps you're on Windows? Yeeeah.. I totally botched some basics on Windows.. `CTRL + C`, is used to show/hide the cursor when the editor is hidden... thus it breaks a really crucial default copy function... (Q: are you allowed to copy+paste while live coding?! jk). I also use `CTRL + T` for tidying the code.. but I think on Windows that opens a new Tab instead. I shooould use a VM for testing... I suppose the really nice thing to do, would be make the shortcuts editable and stored in the settings. Not sure how easy that would be to interpret in my keydown listener code. But I was also interested in letting Mac users switch to using 'CMD' though surely same issue, of ones that aren't allowed due to system/browser. I use `CTRL + SHIFT + _` for adding snippets like audio and OSC... so I'd prefer to avoid that extra modifier.

Suggestions?

**Comment by ffd8** [comment]
Wow, just found the [mousetrap](https://craig.is/killing/mice) library = crazy cool.
Maybe I can use this to nicely let people customize their environment (with my suggested defaults).

**Comment by ffd8** [comment]
Many thanks for working out tthese various ideas. Gotta say, the Edit vs Command Mode doesn't sound so user friendly, unless one comes from a VIM background – which I myself don't, nor any of my students who have usually never touched code, let alone CLI. That openvim link was great and I see the speed advantages when one is used to it, but I want to keep it more accessible. Not to mention on a Mac.. at least for now with this dumb touchbar.. my ESC key is super volatile 🤪😭.

However, you bring up a great point – I kind of see the edit/command mode as being when one toggles the editor as being visible or hidden, so there's no reason shortcuts like `CTRL + C` (toggle cursor when editor is hidden) should do anything while the editor is visible. Of course `CTRL + T` tidying code is something for only while the editor is visible (since it's locked when hidden).. so that just might need a personal remapping from the user on a windows machine. To be honest, it is Mac biased, as I'm developing on (and 99% of my students) are on mac laptops = no home/end keys to even know I'm missing that start/end of line shortcut. Soooo maybe a shortcuts pref panel, which lets one remap would be a decent compromise. The request for allowing VIM already came up – but is def a special case and would kill all the other keybindings = with such a pref pan... could potentially work around them.

**Comment by ffd8** [comment]
Custom keyboard shortcuts are here! #37

**Comment by geneticmoo** [comment]
Please can you just change CTRL+C to CTRL+K or something (anything!) else. Also CTRL+A is a universal one. 
The user defined custom keyboard shortcuts is glitchy and very hard to use on Windows. 
I'd like to introduce this amazing environment to many people in workshops but this messy setting up business is putting me off.

Thanks

**Comment by ffd8** [comment]
@geneticmoo – sure I'll look into changing these in the next release. Ran into this issue in the past two workshops, where indeed it breaks a few keys for PC/Linux users– though it was a quick fix by setting custom shortcut keys- shouldn't be necessary to do so (maybe need to analyse browser/OS and adjust metakeys). Did you try setting custom shortcuts within the settings panel? Curious what issues you run into when trying to manually set shortcut keys.. hopefully you can just click and create new ones, ie adding SHIFT.

**Comment by geneticmoo** [comment]
Yes - but the customs shortcuts is inconsistent and hard to use.

when you click on the Cursor Toggle line it goes green and then I'd expect pressing CTRL+K at the same time to change it. But it doesn't - you have to just press the C and then change it to K.

So then - on another line (CTRL+A is also reserved by Windows - select All) - assuming you only click on one thing at a time (ie CTRL or A) this time trying to change the CTRL to SHIFT does something different. It changes the whole line to SHIFT. And from then on I can't change this to anything else - so have to reset the whole of P5Live to start again.

So there is some inconsistency in how it works.
________________________________
