### ISSUE TITLE
Feature request: Support multiple files

### ISSUE THREAD

**Issue by guidobouman** [ffd8/P5LIVE#53]
When doing a hackathon with multiple artists, the main sketch gets a rather big quite quickly:
- Actual animation (simple dot animations based on lissajous demo)
- Multiple shaders (rgb split, scanlines, blur, bloom) 
- MIDI sharing (with SyncData)
- Variable persistence (custom local cache)

The option to split the code into different files like with p5.js online editor would be really nice!

How do you think that could work?

**Comment by guidobouman** [comment]
Added bonus: the editor gets REALLY slow when it has over 300 linea of code. The thread freezes for about 2 seconds after each keystroke. A recorded profile shows that the problem is in the ACE editor keydown handle, not sure why.

**Comment by ffd8** [comment]
Curious how this would work simply, while not expanding the codebase/complications of sync in cocoding in crazy way. At the moment, there's only the one single ace editor contents being synced (using [peeredit](https://github.com/jorendorff/peeredit) which is linked directly to ace editor instance). All sorts of things like cursor position, deltas etc are linked to this... potenitally it could be written as a class - where additional instances are possible – keeping track of which ace-editor one is working in? Or is there a way to semi fake it, with the appearance of multiple windows/tabs/whatever – but really it's a singular text block? Because when you 'clone the sketch' for saving locally – which window would it save?? 

There's lots of reasons to use the p5 online editor (particularly assets and split scripts) – in P5LIVE, easy/speed/vj/minimal_interface etc are given priority. So I'm def up for exploring the idea, but would have to avoid being invasive for user (since this needs to work as well for total beginner as pro user).

Re: lag out after lots of lines of code.. strange – are you speaking just of the cocoding context? I have a few sketches with 1000+ lines of code and never ran into issues. Be sure the background color to your editor code is fully opaque. Nevertheless, would be interesting to isolate the issue–  best to open a another issue and try sharing some demo code where it occurs.

**Comment by ffd8** [comment]
For now I'm going to close this, since I don't have plans to implement a function for multiple-files.. in that case, it's best to use the p5 web-editor, glitch.com, or working locally with a syntax highlighter... 

Regarding the lag.. please feel free to open a new issue – curious if it's something with ACE that's been resolved in the meantime (I try to keep up to date with their latest version) or more likely, something about the syncing of ACE over websockets (using peeredit as linked above) and maybe that slowly bogging down with a big history? Been looking for a way to cleanly purge/reset the synced history if getting too long (with garbage that no longer needs to be synced) – but haven't found a way just yet...

**Comment by guidobouman** [comment]
Thanks for getting back to this issue. Not using it right now. Will try to do a collaborative hack session again some time soon. Will let you know how it fares!
