### ISSUE TITLE
obsolete socket.io contains a high severity vulnerability (Resource exhaustion in engine.io)

### ISSUE THREAD

**Issue by SableRaf** [ffd8/P5LIVE#73]
npm audit returns the following

```
# npm audit report

engine.io  <4.0.0
Severity: high
Resource exhaustion in engine.io  - https://github.com/advisories/GHSA-j4f2-536g-r55m
fix available via `npm audit fix --force`
Will install socket.io@4.4.1, which is a breaking change
node_modules/engine.io
  socket.io  1.0.0-pre - 2.4.1
  Depends on vulnerable versions of engine.io
  node_modules/socket.io

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by ffd8** [comment]
Hey @SableRaf - awesome and thanks for the heads up! Github shows me an issue with the marked.js lib that needs to be updated, but hadn't seen anything on this. Will add to que of next version update.

**Comment by ffd8** [comment]
FYI – still hadn't had time to update socket.io to v3+ since there's some breaking changes and focus was elsewhere. Nevertheless, had run an `npm audit fix` (not --force), which cleared things up. 

Closing for now since there's no high severity issues and hopefully the COCODING engine upgrade to Yjs will take place sometime in the near future...
