### ISSUE TITLE
[feature request] more ace themes

### ISSUE THREAD

**Issue by SableRaf** [ffd8/P5LIVE#74]
It would be nice to have a larger choice of themes for the editor. I managed to add the [monokai theme for Ace 1.4.12](https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/theme-monokai.min.js) which mostly works, but the line focus makes the text disappears and I couldn't find where to fix it.

**Comment by SableRaf** [comment]
Ok, I figured out it was a matter of changing the ace_active-line property in theme-monokai.js. I'll do a pull request :)

**Comment by ffd8** [comment]
@SableRaf thanks for the nudge on this. The first version of P5LIVE had all the dark Ace themes, but soon dropped most due to visual/contrast issues, especially due to my weird hacky decision (via CSS) to force the text to be white to help contrast with most themes. I have had one request for a light-mode and sure, why not let people use the whole set?! I'll hold off on your PR for now, since this should include even more themes and the ability to disable/customize this text color, allowing the theme to override it or use whatever one wants. I have a few other small updates to share, but have been AFK the past few weeks, so I'll add this to the next version. Until then, enjoy tricking out your offline version!

**Comment by ffd8** [comment]
> Ok, I figured out it was a matter of changing the ace_active-line property in theme-monokai.js. I'll do a pull request :)

Aha - yet another option that this update should probably include, customizing the highlight color (which was a problem with a buncha themes and readability)

**Comment by julesvirallinen** [comment]
Just chiming in to say that in the VJ world the forced white is bad, as white lights up a room way more than anything else. I've hacked out the override but something to keep in mind!

**Comment by ffd8** [comment]
@julesvirallinen whaaat, you don't want your code blaring the retina of the audience?! you probably found it, but within the `style.css`, go down to `.p5-ta, #p5-editor` and disable `color:#fff;`

yupyup, will def be a part of the next update, ALL the themes and ability to toggle/force a fixed color for non-colorized text (currently white), since it seems like many themes leave a lot of text without styling, which can become invisible depending on visuals/bg behind it. currently got sidetracked re-working the 'snippets' idea to make it way easier to add/customize them.. then back to this...

![image](https://user-images.githubusercontent.com/570957/201539136-b000f6bc-0874-4100-82ab-87f5a512ada9.png)

**Comment by ffd8** [comment]
@SableRaf - FYI, the latest 1.5.0 release now has allll the themes + @julesvirallinen there's also customization for if it uses the theme's built in text coloring (many are a gray), or if you want a custom color for non highlighted text (which was previously white, but can now be any color) + if one wants the currently focused line of code to have a highlight color or not. cheers!
