### ISSUE TITLE
Co-coding users' cursors are not visible

### ISSUE THREAD

**Issue by SableRaf** [ffd8/P5LIVE#76]
In co-coding mode, my coding partners' cursors appears briefly at the start of a session then disappear almost instantly and cannot be seen again.

OS: Windows 10
Browser: Chrome Version 100.0.4896.127

**Comment by SableRaf** [comment]
Ok nevermind I understand that this only appears when you hover on the person's name. Would be a nice feature to allow it to be permanent but that should be a feature request. I'll close this.

**Comment by ffd8** [comment]
Hey @SableRaf – exactly, initially it was always visible, but I noticed when teaching with a group of 25+ students, it would lag a few students setups (prob based on older laptop, OS, browser)– so I decided to make it 'on demand' = just leave your cursor over the `user list` (no specific person, in general the whole list) and you'll see all of them (can keep coding away too). Moving the mouse away from there hides them if you notice a hit in performance (really only the case when having 20+). Perhaps rather than a setting/checkbox, I could make it so that if there's more than 4-5 people in the room, the cursors auto-toggle, otherwise they stay on, which would be useful for when jamming with just a few folks....

**Comment by ffd8** [comment]
@SableRaf - PS, I'm nearly ready to share early access for my latest [COCODING Classroom](https://cocodingclassroom.cc) – which is specialized for teaching a group of students (whereas COCODING in P5LIVE is/will be more intended for jamming with just a few or a whole group). 

[Register here](https://forms.gle/JFMoZbhXxVitXJLL7) for early access.
